import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/css/style.css";
import { MyContextProvider } from "@/constants/context/MyContext";
import { contractData } from "@/constants/utils/data";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MyContextProvider data={contractData}>{children}</MyContextProvider>
      </body>
    </html>
  );
}
